version: '2.1'
services:
  browsertests:
    build: .
    container_name: sample-login-geb-spock-tests
    volumes:
      - .:/home/app
    command: mvn clean test -Dgeb.env=seleniumchrome
    depends_on:
      seleniumchrome:
        condition: service_healthy

  seleniumchrome:
    image: selenium/standalone-chrome
    container_name: selenium-chrome
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail -X HEAD http://localhost:4444/wd/hub"]
      interval: 3s
      timeout: 12s
      retries: 30

